djangocrm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls', namespace="leads")),
]

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
    path('',views.home_page,name='lead-list'),
    path('leads/create/',views.create_leads,name='lead-create'),
    path('leads/<int:pk>/',views.lead_detail,name='lead-detail'),
    path('leads/<int:pk>/update/',views.lead_update, name='lead-update'),
    path('leads/<int:pk>/delete/',views.delete_lead,name='lead-delete'),
    


]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.email
    

class leads(models.Model):

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent" , on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
        

leads/forms.py
from django import forms
from .models import leads

class leadmodelform(forms.ModelForm):
    class Meta:
        model  = leads
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )

class leadform(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

leads/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from leads.models import Agent,leads
from .forms import leadform,leadmodelform

# Create your views here.

def home_page(request):
    #return HttpResponse("Hellow Worlld")
    lead = leads.objects.all()
    context ={
        "leads" : lead
    }
    return render(request, 'leads/home_page.html' , context)

def lead_detail(request,pk):
    lead_detail_view = leads.objects.get(id=pk)
    context = {
        "lead_detail_view1" : lead_detail_view
    }
    return render(request , 'leads/leads_details.html' , context)

def create_leads(request):
    print(request.POST)
    if request.method =="POST":
        print("Reciving post request")
        form = leadmodelform(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    context = {
        "form" : leadmodelform()
    }
    return render(request , 'leads/create_leads.html',context)

def lead_update(request,pk):
    lead = leads.objects.get(id=pk) 
    form = leadmodelform(instance=lead)
    if request.method =="POST":
        print("Reciving update post request")
        form = leadmodelform(request.POST,instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/")
    context = {
        "lead" : lead,
        "form" : form
    }
    return render(request, "leads/update_leads.html",context)

def delete_lead(request,pk):
    lead = leads.objects.get(id=pk)
    lead.delete()
    return redirect("/")


#def lead_update(request,pk):
#    lead = leads.objects.get(id=pk) 
#    context = {
#        "lead" : lead
#    }
#    print(request.POST)
#    if request.method =="POST":
#        print("Reciving post request")
#        form = leadform(request.POST)
#        if form.is_valid():
#            print("checking if data is valid")
#            print(form.cleaned_data)
#            first_name = form.cleaned_data['first_name']
#            last_name = form.cleaned_data['last_name']
#            age = form.cleaned_data['age']
#            
#            lead.first_name = first_name
#            lead.last_name = last_name
#            lead.age = age
#            lead.save()
#            print('the lead has been created')
#            return redirect("/")
#    context = {
#        "form" : leadform()
#        
#    }
#    return render(request, "leads/update_leads.html",context)


#def create_leads(request):
#    print(request.POST)
#    if request.method =="POST":
#        print("Reciving post request")
#        form = leadmodelform(request.POST)
#        if form.is_valid():
#            print("checking if data is valid")
#            print(form.cleaned_data)
#            first_name = form.cleaned_data['first_name']
#            last_name = form.cleaned_data['last_name']
#            age = form.cleaned_data['age']
#            agent = form.cleaned_data['agent']
#            
#            leads.objects.create(
#                first_name = first_name,
#                last_name = last_name,
#                age = age,
#                agent = agent
#            )
#            print('the lead has been created')
#            return redirect("/")
#    context = {
#        "form" : leadmodelform()
#    }
#    return render(request , 'leads/create_leads.html',context)

leads/templates/leads/create_leads.html
{% extends "base.html" %} 
{% block content %}
    <h1>Create a lead</h1>
    <h1><a href="../../">Return to leads</a></h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type=submit>Submit</button>
    </form>   
        
{% endblock content %}

leads/templates/leads/home_page.html
{% extends "base.html" %} 
{% block content %}
    <h1><a href="{% url 'leads:lead-create' %}">Create New Leadsss</a></h1>
       <ul>
       {% for lead in leads %}
       <li><a href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }} {{ lead.last_name }}</a></br>
       <a href="{% url 'leads:lead-update' lead.pk %}" >Update</a><br><a href="{% url 'leads:lead-delete' lead.pk %}" >Delete</a></li><hr></br>
       {% endfor %}
       </ul>
       
{% endblock content %}

leads/templates/leads/leads_details.html
{% extends "base.html" %} 
{% block content %}
    <a href="{% url 'leads:lead-list' %}">Return to leads</a>
      <h1>Primary Key : {{ lead_detail_view1.pk }}</h1>
      <h1>First Name : {{ lead_detail_view1.first_name }}</h1>
      <h1>Last Name : {{ lead_detail_view1.last_name }}</h1>
      <h1>Age : {{ lead_detail_view1.age }}</h1>
      <h1>Agent : {{ lead_detail_view1.agent }}</h1>
      <h1><a href="{% url 'leads:lead-update' lead_detail_view1.pk %}" >Update</a></h1>
      <h1><a href="{% url 'leads:lead-delete' lead_detail_view1.pk %}" >Delete</a></h1>
        
{% endblock content %}

leads/templates/leads/update_leads.html
{% extends "base.html" %} 
{% block content %}
    <h1>Upadte lead {{ lead.first_name }} {{ lead.last_name }}</h1>
    <h1><a href="{% url 'leads:lead-list' %}">Return to leads</a></h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type=submit>Submit</button>
    </form>   
        
{% endblock content %}

templates/base.html
{% include "header.html" %}
    <body>
    {% include "navbar.html" %}

       {% block content %}
       {% endblock content %}
        
        <script src="" async defer></script>
    </body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  
<!-- Mirrored from prium.github.io/phoenix/v1.13.0/apps/crm/leads.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 14 Sep 2023 11:22:19 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>Phoenix</title>

    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="assets/img/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/img/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicons/favicon.ico">
    <link rel="manifest" href="assets/img/favicons/manifest.json">
    <meta name="msapplication-TileImage" content="assets/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">
    <script src="vendors/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="vendors/simplebar/simplebar.min.js"></script>
    <script src="assets/js/config.js"></script>

    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="vendors/choices/choices.min.css" rel="stylesheet">
    <link href="vendors/flatpickr/flatpickr.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&amp;display=swap" rel="stylesheet">
    <link href="vendors/simplebar/simplebar.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../../../unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link href="assets/css/theme-rtl.min.css" type="text/css" rel="stylesheet" id="style-rtl">
    <link href="assets/css/theme.min.css" type="text/css" rel="stylesheet" id="style-default">
    <link href="assets/css/user-rtl.min.css" type="text/css" rel="stylesheet" id="user-style-rtl">
    <link href="assets/css/user.min.css" type="text/css" rel="stylesheet" id="user-style-default">
    <script>
      var phoenixIsRTL = window.config.config.phoenixIsRTL;
      if (phoenixIsRTL) {
        var linkDefault = document.getElementById('style-default');
        var userLinkDefault = document.getElementById('user-style-default');
        linkDefault.setAttribute('disabled', true);
        userLinkDefault.setAttribute('disabled', true);
        document.querySelector('html').setAttribute('dir', 'rtl');
      } else {
        var linkRTL = document.getElementById('style-rtl');
        var userLinkRTL = document.getElementById('user-style-rtl');
        linkRTL.setAttribute('disabled', true);
        userLinkRTL.setAttribute('disabled', true);
      }
    </script>
  </head>

templates/next_page.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      
        <ul> 
        {% for lead in leads %}
        <li><a href="/leads/{{ lead.pk }}">{{ lead.first_name }}</a></li>
        <li>{{ lead.last_name }}</li>
        <li>{{ lead.age }}</li>
        <li>{{ lead.agent }}</li>
        {% endfor %}
        </ul>
       
        
        
        <script src="" async defer></script>
    </body>
</html>